# Generated by Django 3.2.19 on 2023-05-17 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_id', models.IntegerField(unique=True)),
                ('table_capacity', models.IntegerField(choices=[(2, '2'), (4, '4'), (6, '6'), (8, '8'), (10, '10'), (12, '12'), (20, '20')], default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('booking_time', models.IntegerField(choices=[(1, '1:00pm - 2:50pm'), (2, '3:00pm - 4:50pm'), (3, '5:00pm - 6:50pm'), (4, '7:00pm - 8:50pm'), (5, '9:00pm - 10:50pm')], default=1)),
                ('booking_date', models.DateField()),
                ('booking_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_table', to='booking.table')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_guest', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
