# Generated by Django 3.2.19 on 2023-05-17 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booked_table', to='booking.table'),
        ),
    ]
