# Generated by Django 3.2.19 on 2023-05-17 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_booking_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['table_id']},
        ),
    ]
